language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

install:
  - composer install --dev --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - php vendor/bin/phpcs --standard=PSR2 src/ tests/
  - php vendor/bin/phpmd src/,tests/,examples/,benchmarks/ text codesize,controversial,design,naming,unusedcode
  - php vendor/bin/phpcpd src/ tests/ examples/ benchmarks/
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/athletic -p benchmarks/

after_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then php vendor/bin/coveralls -v; fi"
